# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/comet-generative-agents',
                'doc_host': 'https://andreamunafo.github.io',
                'git_url': 'https://github.com/andreamunafo/comet-generative-agents',
                'lib_path': 'comet_generative_agents'},
  'syms': {'comet_generative_agents.core': {'comet_generative_agents.core.foo': ('core.html#foo', 'comet_generative_agents/core.py')}}}
